nf-core/epitopeprediction

environment.yml

Update Fred2 (bugfix)

---

Dockerfile
environment.yml

Add python markdown dependencies

---

bin/epaa.py
bin/gen_peptides.py
conf/test_proteins.config
main.nf
nextflow.config

Alternative to #33 using Fred2.

Add option to use FASTA files with protein sequences using Fred2

---

bin/epaa.py

The `logging.info()` were not printed, neither to the specified log file nor to the stdout. So far it is not critical for the actual workflow, but since I wanted to add some logging information, this caused some confusion. Did it work before with recent workflow versions?
This is what I found: `logging.basicConfig()` can only be defined once: "This function does nothing if the root logger already has handlers configured for it"(https://docs.python.org/2.7/library/logging.html). My guess is that it is already configured in one of the imported packages in Fred2, such as MHCflurry...? 
The Logging Level was 30, while it should be 10 when set to `DEBUG`.
After creating a new logging object with `getLogger()` this worked for me and all expected logging messages are written to the file …

Fix logging - not use root logger

---

.github/workflows/ci.yml
nextflow.config

Just activated the tests, the `test_proteins.config` file was already added before.

Activated tests for using protein FASTA file as input

---

bin/epaa.py
main.nf

See #36.
Used software version from `get_software_versions` to specify Fred2 predictor version and check if tool version is supported by Fred2 (see #11). 
#

Specify predictor version

---

.github/workflows/ci.yml
bin/epaa.py
conf/test_peptides_h2.config
main.nf
nextflow.config

Mouse allele names do not contain "*", which is used to access the allele results. I added "H-2-" to this. 

Adjust for mouse alleles

---

main.nf

Addresses https://github.com/nf-core/epitopeprediction/issues/40.

Tidy up min/max_peptide_length parameters in summary

---

CHANGELOG.md
bin/check_requested_models.py
bin/check_supp_models.py
bin/epaa.py
docs/output.md
main.nf
nextflow.config

Changes to handle and check supported models:
-  <s>waiting for PR #39 and Fred2 PR</s>
- <s>extra process to write out all supported models (dry-run)</s>
- <s>extra process to check if requested models are supported by selected tools.</s>
- <s>still needs to be tested to use correct predictor versions (once Fred2 PR through) and should be double checked</s>
-  <s>We need to think about the allele formats! It is confusing that currently mouse alleles should be provided in the format "H2-Xx", while human alleles should be provided as "A*01:01"</s>
I added two processes:
1) `showSupportedModels`: calls a python script to print all supported models for the installed predictor tool versions and  (using the output from process `get_software_versions`) and for syfpeithi v1.0. This will be a …

Handle supported models 

---

CHANGELOG.md
bin/epaa.py
bin/merge_jsons.py
docs/output.md
main.nf
nextflow.config
nextflow_schema.json

Add functionality to write out a FASTA file with protein sequences as mentioned in #9 

Add functionality to write fasta with protein sequences

---

README.md
docs/output.md
main.nf

Update docs and fix other things for next release

---

.github/workflows/ci.yml
Dockerfile
environment.yml
nextflow.config

Prepare for release `1.1.0` and bump version.

Prepare release 1.1.0

---

.github/workflows/awstest.yml
README.md
bin/epaa.py
conf/test.config
conf/test_full.config
conf/test_mhcflurry.config
conf/test_mhcnuggets.config
conf/test_peptides.config
conf/test_peptides_h2.config
conf/test_proteins.config
conf/test_variant_tsv.config
docs/output.md
main.nf
nextflow.config

Fixing things mentioned in review for release 1.1.0.

Fix review comments

---

README.md

Fix zenodo badge

---

environment.yml

This PR adds dependencies for the NetMHC tool family to the Docker file ahead of the actual integration.

Add NetMHC tool dependencies ahead of integration

---

bin/epaa.py
main.nf
nextflow.config
nextflow_schema.json

- Implementation of optional threshold customization via a JSON file
- Shifted color variables to the main scope to remove duplicated code. This fixed a bug, which occurs if the user provides non-supported alleles

Threshold customization and color fixes

---

.github/workflows/ci.yml
CHANGELOG.md
CITATIONS.md
bin/epaa.py
bin/merge_jsons.py
modules/local/merge_json.nf
modules/local/split_peptides.nf
workflows/epitopeprediction.nf

port python 2 scripts to python 3

---

modules/local/peptide_prediction.nf
modules/local/show_supported_models.nf

Fix AWS megatests

---

workflows/epitopeprediction.nf

- Fixes bug occurring when running pipeline on AWS batch

Fix AWS test

---

conf/base.config
modules/local/cat_files.nf

Fixes yet another AWS bug by adding a container to the CAT_TSV process.

Fix AWS II

---

CHANGELOG.md
nextflow.config

Bump version to 2.1.0dev

---

CHANGELOG.md
bin/epaa.py
bin/merge_jsons.py

This extends the JSON prediction report with the applied tool thresholds to make sure to keep user-defined thresholds for reproducibility.

Add threshold to report

---

CHANGELOG.md
bin/epaa.py
conf/test_full.config
conf/test_mhcnuggets.config

Add tools to full size test

---

CHANGELOG.md
nextflow.config

bump version

---

.editorconfig
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
.github/workflows/linting.yml
CHANGELOG.md
CITATION.cff
README.md
assets/email_template.txt
bin/check_requested_models.py
bin/check_samplesheet.py
bin/check_supported_models.py
bin/epaa.py
bin/gen_peptides.py
bin/merge_jsons.py
bin/split_peptides.py
bin/split_vcf_by_variants.py
conf/base.config
docs/usage.md
lib/WorkflowEpitopeprediction.groovy
lib/WorkflowMain.groovy
main.nf
modules.json
modules/nf-core/modules/custom/dumpsoftwareversions/templates/dumpsoftwareversions.py
nextflow.config
pyproject.toml

This 
- updates to template `2.5.1`
- solve merge conflicts
- includes `Black` code formatting
- updates the `Ensembl GRCh38` reference source.

Merge template update 2.5.1

---

CHANGELOG.md
modules.json
modules/nf-core/modules/custom/dumpsoftwareversions/main.nf
modules/nf-core/modules/custom/dumpsoftwareversions/templates/dumpsoftwareversions.py
modules/nf-core/modules/multiqc/main.nf
modules/nf-core/modules/multiqc/meta.yml
workflows/epitopeprediction.nf

This
- updates the nf-core modules `multiqc` and `dumpsoftwareversions`
- adapts the `multiqc` call in the pipeline.

Update nf-core modules

---

CHANGELOG.md
nextflow.config

bump version to 2.2.1

---

CHANGELOG.md
README.md
bin/epaa.py
bin/gen_peptides.py
bin/merge_jsons.py
bin/split_peptides.py
bin/split_vcf_by_variants.py

Release 2.2.1 bugfix

---

CHANGELOG.md
README.md
nextflow_schema.json

Remove duplication in README and genome reference enum

---

CHANGELOG.md
modules/local/cat_files.nf
modules/local/csvtk_concat.nf
modules/local/epytope_check_requested_models.nf
modules/local/epytope_generate_peptides.nf
modules/local/epytope_peptide_prediction.nf
modules/local/external_tools_import.nf
modules/local/get_prediction_versions.nf
modules/local/merge_json.nf
modules/local/snpsift_split.nf
modules/local/split_peptides.nf
modules/local/variant_split.nf

Making sure that `nextflow run main.nf -profile test,docker -stub --outdir test_stub` successfully runs for the new `nf-core download` CI test

Add stubs to all local modules

---

README.md
assets/schema_input.json
bin/fasta2peptides.py
bin/split_peptides.py
conf/modules.config
modules/local/fasta2peptides/main.nf
modules/local/merge_predictions/environment.yml
modules/local/merge_predictions/main.nf
modules/local/merge_predictions/templates/merge_predictions.py
modules/local/merge_predictions/templates/versions.yml
modules/local/mhcflurry/main.nf
modules/local/mhcnuggets/environment.yml
modules/local/mhcnuggets/main.nf
modules/local/netmhciipan/main.nf
modules/local/netmhcpan/main.nf
modules/local/prepare_prediction_input/environment.yml
modules/local/prepare_prediction_input/main.nf
modules/local/prepare_prediction_input/templates/prepare_prediction_input.py
modules/local/split_peptides/main.nf
modules/local/unpack_netmhc_software/main.nf
nextflow.config
subworkflows/local/mhc_binding_prediction/main.nf
workflows/epitopeprediction.nf

Include feedback for mhc-binding-workflow #260

---

docs/usage.md

I think it should be like this. It's bothering me for a while now

fix file endings in samplesheet

---

docs/output.md
nextflow_schema.json
workflows/epitopeprediction.nf

The `--fasta_output flag `allows for the generation of FASTA files directly from input VCF variants. Since this does not require MHC binding prediction, this PR adds a conditional to skip the prediction steps.

Skip prediction if fasta_output flag is set

---

CHANGELOG.md
bin/summarize_results.py
conf/modules.config
modules/local/merge_predictions/templates/merge_predictions.py
modules/local/prepare_prediction_input/templates/prepare_prediction_input.py
nextflow.config

Fixes for https://github.com/nf-core/epitopeprediction/issues/288 and #294

Fix duplication in summarized dataframe
