nf-core/epitopeprediction

- bin/scrape_software_versions.py
- main.nf
Added versions for Fred2 and MHCnuggets to `get_software_versions()` (#37). We will need that to control the used Fred2 predictor classes. 
#
> Added software versions for Fred2 and MHCnuggets.

- CHANGELOG.md
- environment.yml
Update Fred2.
Maybe we can improve the changelog in another PR.
> Update Fred2 from version 2.0.6 to 2.0.7

- conf/test_peptides_h2.config
Changed `test_peptides_h2` to use `mhcnuggets-class-1` instead of `syfpeithi`, since Fred2 v2.0.7 does not yet support mouse alleles for Syfpeithi (Syfpeithi itself does).
> Adjusted test for mouse allele to use mhcnuggets

- CHANGELOG.md
- bin/epaa.py
Hi @christopher-mohr ,
I have a question regarding the affinity values. As far as I understood, the output score from `mhcnuggets` and `Fred2` are `IC50` values, which can get converted to affinity values in [0,1] with `1.0 - log_50000(IC50)`.
The `50000^(1.0-j)` conversion I would expect if already affinity values in [0,1] are given, to convert it back to IC50 values, but that is not the case for both `mhcnuggets` and `mhcflurry`. Not sure, do I miss anything here, otherwise I would change it accordingly.
Still, I guess the score values and thresholds between the tools or alleles are not really comparable. Also `netMHC` uses `percentile rank scores` computed based on random natural peptides. Could we maybe provide a similar score here? 
**Learn more about contributing:** …
> Fix computation of mhcnuggets and mhcflurry score

- bin/epaa.py
The problem was the merging process of the method-specific prediction result data frames when using multiple prediction tools. Using the `panda` method `concat` seems to solve the problem. However, so far I am not sure why the code didn't work anymore.
> Fix predictions with multiple methods, small improvements

- CHANGELOG.md
- bin/epaa.py
This should add functionality to add metadata provided with variants dynamically without being limited to a set of (hardcoded) metadata fields. Which information from VCF files should we store and write to the results table? Currently, the information from the `INFO` column is used but we could additionally store the genotype-specific information, e.g. in the following line that would be the information given for `NORMAL` and `TUMOR`.
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NORMAL	TUMOR
chr1	12954870	.	C	T	.	PASS	NT=ref;QSS=52;QSS_NT=52;SGT=CC->CT;SOMATIC;TQSS=1;TQSS_NT=1;ANN=T|missense_variant|MODERATE|PRAMEF10|ENSG00000187545|transcript|ENST00000235347|protein_coding|3/4|c.413G>A|p.Cys138Tyr|493/1525|413/1425|138/474||	DP:FDP:SDP:SUBDP:AU:CU:GU:TU	414:0:0:0:0,0:413,425:0,0:1,4 …
```
> Use additional metadata

- CHANGELOG.md
The link to zenodo was broken.
> Fix link to zenodo

- main.nf
`ch_alleles` and `ch_check_alleles` being queue channels causes the pipeline to process only one chunk in the `peptidePrediction` process. Fix attached.
> Make alleles channels value channels

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- bin/decrypt
- bin/epaa.py
- bin/scrape_software_versions.py
- conf/test_netmhc.config
- conf/test_netmhcii.config
- conf/test_netmhciipan.config
- conf/test_netmhcpan.config
- docs/output.md
- main.nf
- nextflow.config
- nextflow_schema.json
This patch adds support for the non-free 3rd party tools NetMHC, NetMHCpan, NetMHCII and NetMHCIIpan. Since the tools' licenses do not allow for redistribution of the software, the user has to provide the software tarball which can be obtained from the upstream website.
* To maintain reproducibility, the pipeline validates the checksum of the provided software tarballs
* The patch provides a process that
* Unpacks the software tarballs
* Performs necessary modifications to the tools wrapper scripts as required by the installation instructions
* Downloads the model data as required by installation instructions. Again, checksums are being checked.
* `epaa.py`: Make tool name comparison case insensitive. Unfortunately, the method names aren't uniform w.r.t. upper / lower case letters among …
> Add support for the non-free netMHC tool family

- conf/test.config
- conf/test_full.config
- conf/test_mhcflurry.config
- conf/test_mhcnuggets.config
- conf/test_netmhc.config
- conf/test_netmhcii.config
- conf/test_netmhciipan.config
- conf/test_netmhcpan.config
- conf/test_peptides.config
- conf/test_peptides_h2.config
- conf/test_proteins.config
- conf/test_variant_tsv.config
This changes the deprecated Input parameters to `input` and uses the available test-dataset sample sheets.
> Adapt input parameter and paths in test configs to sample sheet

- bin/check_samplesheet.py
- subworkflows/local/input_check.nf
- workflows/epitopeprediction.nf
This changes the validation and parsing of the sample sheet and moves parts of the functionality up to `input_check.nf` where we can access the file contents and therefore determine the input type that is given. No additional sample sheet columns are written anymore and  `input type` is forwarded through the `meta` map.
Some variable names in `epitopeprediction.nf` are changed and adapted.
> Change sample sheet validation and parsing

- CHANGELOG.md
- conf/test_full.config
- workflows/epitopeprediction.nf
This changes the sample sheet that is used for the full test and fixes a bug in the combination of channels for the prediction model checks.
> Adapt full test profile

- .github/workflows/ci.yml
- nextflow.config
- workflows/epitopeprediction.nf
This removes the support for the tools netmhcII and netmhcIIpan since the versions that supported by FRED2 are not provided anymore by the developer of the netmhc tools. We will probably add more recent versions of these tools again later.
I kept the parameters for the tool executables and the test profiles, but we can discuss if it would be better to remove these as well for now.
> Remove netmhcii specs and deactivate corresponding tests

- bin/epaa.py
- docs/output.md
- modules/local/cat_files.nf
Initialize empty protein list for peptide input case and fix file extension retrieval in the `cat` process.
> Fix FASTA generation

- conf/modules.config
This changes the result folder structure to the following
```
.
+-- predictions
|   +-- sample1
|         +-- predictions.tsv
|   +-- sample2
...
+-- split_predictions
|   +-- sample1
...
+-- split_input
|   +-- sample1
...
```
So I guess it should be more obvious where to find the final results and the results are grouped by sample. In case of protein input there will be a folder `generated_peptides` which has been created as `fred2` before. 
What do you think @ggabernet @marissaDubbelaar @jonasscheid ? If you agree, I will still change the documentation accordingly.
Fixes #131 
- [x ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
> Change result folder structure

- CHANGELOG.md
- bin/epaa.py
Minor change:
Some variants in SnpEff (v.4.3t) contain a `LOF` flag, which altered the dynamic structure of variant annotations. Since most variants do not have this flag, it caused an error. In general, the pipeline crashes, when a variant has metadata, which other variants don't have.
This PR closes #136
> Fix unique variant annotation field handling #136

- .nf-core.yml
Add lint config to make linting pass which currently fails due to change for markdown linting which is needed until the next nf-core release is available.
> Add lint config

- CHANGELOG.md
- bin/epaa.py
This adds a check during VCF file parsing whether the specified format entry is given for the respective genotypes.
Fixes #142.
> Check FORMAT entries in VCF parser

- CHANGELOG.md
- conf/modules.config
- modules.json
- modules/local/snpsift_split.nf
- modules/nf-core/modules/gunzip/main.nf
- modules/nf-core/modules/gunzip/meta.yml
- subworkflows/local/input_check.nf
- workflows/epitopeprediction.nf
This adds support for gzipped VCF file input. Fixes #143. 
- add nf-core/gunzip module
- handle gzipped VCF files in workflow
- fix snpsift version print in the module
> Support gzipped variant input

- bin/epaa.py
- modules/local/peptide_prediction.nf
The new release of epytope (v3.0.0) provides an altered prediction structure due to the incorporation of rank metrics.
This PR aims to embed the new prediction structure in the `epaa.py` script, which is called by the `PEPTIDE_PREDICTION` process.
Related issues:
#54 
#130
> Epytope switch in process peptide_prediction

- CHANGELOG.md
- bin/split_vcf_by_variants.py
- conf/modules.config
- modules/local/variant_split.nf
- nextflow.config
- nextflow_schema.json
- workflows/epitopeprediction.nf
This
- adds the functionality to split input VCF files by variants in order to e.g. create smaller input chunks than with splitting by chromosome. Splitting can be configured with two new parameters `split_by_variants_size` and `split_by_variants_distance`.
- adresses #140
> Add functionality for splitting input VCF files by variants

- assets/external_tools_meta.json
- bin/check_requested_models.py
- bin/epaa.py
- nextflow.config
- nextflow_schema.json
- workflows/epitopeprediction.nf
This 
- adds a JSON file for external prediction tools meta data
- adapts the workflow code, schema, etc accordingly
With these changes, it is currently required to specify the version with the external prediction tool by the user (`--tools netmhcpan-4.0`). It might be better to have default versions of the external prediction tools, e.g. if someone specifies `netmhc`, it would use the most recent version.
> add config for external prediction tools

- bin/check_requested_models.py
- bin/epaa.py
- modules/local/epytope_peptide_prediction.nf
- modules/local/get_prediction_versions.nf
- workflows/epitopeprediction.nf
This fixes a bug that occurred during the pipeline execution for multiple samples of the same input type. The prediction process was only executed once in these cases.
> Fix execution for multiple samples of same input type

- .github/workflows/ci.yml
- CHANGELOG.md
- bin/epaa.py
- conf/test_grch38_variant_tsv.config
- modules/local/epytope_check_requested_models.nf
- modules/local/epytope_generate_peptides.nf
- modules/local/epytope_peptide_prediction.nf
- modules/local/epytope_show_supported_models.nf
- modules/local/get_prediction_versions.nf
- nextflow.config
This 
- changes the `epytope` container versions to the most recent version `3.1.0` (1)
- changes the `Ensembl BioMart` archive version for GRCh38 (2).
Some background to (2):
At some point we decided to stick to specific archive versions of `Ensembl BioMart` because they kept on changing database fields (names) in new versions which broke our pipeline. Now they retired the archive version for `GRCh38` we were using (Ensembl Archive 87, Dec 2016). For now, I switched to the next version (March 2017) since I assumed this has least changes. I still had to adapt some of the database field names in the `epaa.py`. 
At some point we should switch to more recent version and maybe also think about on how to deal with different (user selected?) versions. The version of the `Ensembl BioMart` can …
> Update to epytope 3.1.0

- assets/external_tools_meta.json
This PR increments the number of supported netmhc tools for class 1 and 2 for linux and Mac OS based systems:
- NetMHCpan 4.1
- NetMHCII 2.2 (Mac OS)
- NetMHCII 2.3
- NetMHCIIpan 4.0
- NetMHCIIpan 4.1
For further documentation:
NetMHCIIpan 4.1 (Darwin & Linux) provid the data folder within the software tar, however we did not yet work around this problem. I just thought it would be of nice to have it in order to come up with a solution for this specific version. Meaning the data url and md5 will be deleted most likely.
> Increment support of netmhc tools

- bin/epaa.py
- bin/merge_jsons.py
- modules/local/peptide_prediction.nf
This fixes a bug that occurs when no predictions are available for one part of the initial input (split input) e.g. for unsupported chromosomes (undefined genomic regions). In this case, the prediction result file of this part will only contain basic information with the corresponding column headers but no predictions. If this files happens to be the first in the `csvtk concat -t` command, the resulting full prediction file will only include the basic information and no predictions.
> Fix bug that results in empty prediction results

- CHANGELOG.md
- bin/check_samplesheet.py
- bin/epaa.py
- bin/merge_jsons.py
- conf/modules.config
- conf/test_full.config
- docs/usage.md
- modules/local/cat_files.nf
- modules/local/epytope_check_requested_models.nf
- modules/local/epytope_generate_peptides.nf
- modules/local/epytope_peptide_prediction.nf
- nextflow.config
- nextflow_schema.json
- subworkflows/local/input_check.nf
- workflows/epitopeprediction.nf
This
- adds the functionality to process MHC class information given in the sample sheets in order to perform prediction for multiple mhc classes in the same run
- introduces two new parameters  (`max_peptide_length_class2`,`min_peptide_length_class2`) for providing peptide length for class I and class II peptides independently 
- removes the parameter `mhc_class`
- extends documentation
> Add functionality for prediction with multiple classes in one run

- CHANGELOG.md
- bin/epaa.py
This adds a binder column that holds the information whether the corresponding peptide is a predicted binder to any of the given HLA alleles. With the additional column it is easier to filter the result for binding peptides.
> Add general binder column

- assets/external_tools_meta.json
This changes the version property of `netmhcpan_darwin 4.1` to the correct one.
> Fix external tool version

- CHANGELOG.md
- bin/check_samplesheet.py
- bin/epaa.py
- modules/local/epytope_peptide_prediction.nf
> Logging to stdout and better errors

- .github/workflows/ci-external.yml
- .github/workflows/ci.yml
- .github/workflows/fix-linting.yml
- .github/workflows/linting_comment.yml
- CHANGELOG.md
- lib/WorkflowMain.groovy
- modules.json
- modules/local/cat_files.nf
- modules/local/csvtk_concat.nf
- modules/local/csvtk_split.nf
- modules/local/epytope_check_requested_models.nf
- modules/local/epytope_generate_peptides.nf
- modules/local/epytope_peptide_prediction.nf
- modules/local/epytope_show_supported_models.nf
- modules/local/external_tools_import.nf
- modules/local/get_prediction_versions.nf
- modules/local/merge_json.nf
- modules/local/samplesheet_check.nf
- modules/local/snpsift_split.nf
- modules/local/split_peptides.nf
- modules/local/variant_split.nf
- modules/nf-core/custom/dumpsoftwareversions/main.nf
- modules/nf-core/custom/dumpsoftwareversions/templates/dumpsoftwareversions.py
- modules/nf-core/gunzip/main.nf
- modules/nf-core/multiqc/main.nf
- nextflow.config
- nextflow_schema.json
- workflows/epitopeprediction.nf
Template update and Nextflow version bump in ci.
> Merge template update

- CHANGELOG.md
- bin/check_samplesheet.py
- subworkflows/local/input_check.nf
- workflows/epitopeprediction.nf
The [RowChecker](https://github.com/nf-core/epitopeprediction/blob/b0f0d7a5b3cd352e548901e4cc19937c73add465/bin/check_samplesheet.py#L16) class we could use to check the basic validity of the input.
> Check sample sheet uses Row Checker class

- bin/check_requested_models.py
- bin/check_samplesheet.py
- bin/epaa.py
Now allele data as an internet link can also be used in pipeline. 
Restoring the functionality of the previous PR.
> Allele data can also be used via internet link in sample sheet

- CHANGELOG.md
- bin/check_requested_models.py
- bin/check_samplesheet.py
- bin/epaa.py
- conf/modules.config
- modules/local/merge_predictions.nf
- modules/local/mhcflurry.nf
- modules/local/mhcnuggets.nf
- modules/local/netmhciipan.nf
- modules/local/netmhcpan.nf
- modules/local/prepare_prediction_input.nf
- modules/local/syfpeithi.nf
- subworkflows/local/input_check.nf
- subworkflows/local/mhc_binding_prediction.nf
- workflows/epitopeprediction.nf
Update general structure of MHCbinding subworkflow according to this flowchart.
This is just the bare minimum structure without the prediction functionality. 
- We started with the mhc binding subworflow only for the peptide input type and only for the single input type (implementation for all kinds of inputs will follow)
- The nf core modules for the new subworkflow were added, the functionality will be implemented in the py files corresponding to the modules or in the modules itself
- The mhc binding subworkflow as separate workflows
- The pipeline runs through without functionality `--with-stub`
- The threshold handling will happen in the prepare_prediction_input step
> New structure of mhc binding subworkflow 

- CHANGELOG.md
- modules/local/external_tools_import.nf
This PR is a quick fix for small bug that has been introduced with the new template update. `Quay.io` is now the standard container registry, but for `EXTERNAL_TOOLS_IMPORT`  `biocontainers/biocontainers:v1.2.0_cv1` is used. If `docker.io` is specified it takes precedence.
> Fix external tools import container

- conf/modules.config
- modules/local/epytope_check_requested_models.nf
- modules/local/epytope_generate_peptides.nf
- modules/local/epytope_peptide_prediction.nf
- modules/local/external_tools_import.nf
- modules/local/merge_predictions.nf
- modules/local/merge_predictions/main.nf
- modules/local/merge_predictions/templates/merge_predictions.py
- modules/local/merge_predictions/templates/versions.yml
- modules/local/netmhcpan.nf
- modules/local/prepare_prediction_input/main.nf
- modules/local/prepare_prediction_input/templates/prepare_prediction_input.py
- nextflow.config
- nextflow_schema.json
- subworkflows/local/mhc_binding_prediction.nf
- subworkflows/local/utils_nfcore_epitopeprediction_pipeline/main.nf
Implementing first draft of netmhcpan #216 
PR covers:
- Initial draft of predctor input parsing module
- Loading netmhcpan binary
- Executing netmhpan
- Initial draft of prediction output merging module
Custom scripts for parsing use the nextflow `templates` function
> Initial setup of netmhcpan module

- conf/modules.config
- modules/local/external_tools_import.nf
- modules/local/merge_predictions/templates/merge_predictions.py
- modules/local/netmhciipan.nf
- modules/local/netmhcpan.nf
- modules/local/prepare_prediction_input/templates/prepare_prediction_input.py
- nextflow.config
- nextflow_schema.json
- subworkflows/local/mhc_binding_prediction.nf
- workflows/epitopeprediction.nf
Initial draft of NetMHCIIpan module #250 
- Implements newest version 4.3e
- Initial parsing around the module
- Breaks current main workflow. Needs to get adjusted in future PRs.
- WIP: Supported allele checks that should be handled in local utils subworkflow
> Add initial draft of netmhciipan module

- conf/modules.config
- modules/local/merge_predictions/templates/merge_predictions.py
- modules/local/mhcflurry.nf
- modules/local/prepare_prediction_input/templates/prepare_prediction_input.py
- nextflow_schema.json
- subworkflows/local/mhc_binding_prediction.nf
Add initial mhcflurry module #215 #205
- Download functionality is implemented in the module itself and will be only called once. Models are always stored in `~/.local/share/mhcflurry/<release>`. Unfortunately, that cannot be changed
- MHCflurry `presentation_percentile` is used as metric to define a binder ( see [Paper](https://www.cell.com/cell-systems/fulltext/S2405-4712(20)30239-8?dgcid=raven_jbs_etoc_email) ) 
- Newest 2.1.4 version is currently not usable via conda due to [dependency issues](https://github.com/bioconda/bioconda-recipes/pull/52840)
- Check for supported alleles will be implemented in future PRs
- Tests will be implemented in future PRs
> Add initial mhcflurry module

- conf/modules.config
- modules/local/merge_predictions/templates/merge_predictions.py
- modules/local/mhcnuggets/main.nf
- modules/local/mhcnuggets/templates/mhcnuggets.py
- modules/local/netmhciipan.nf
- modules/local/prepare_prediction_input/templates/prepare_prediction_input.py
- nextflow_schema.json
- subworkflows/local/mhc_binding_prediction.nf
- subworkflows/local/utils_nfcore_epitopeprediction_pipeline/main.nf
Preliminary implementation  of mhcnuggets module #214
> Add mhcnuggets module and harmonize prediction outputs

- CHANGELOG.md
- modules.json
- modules/nf-core/bcftools/stats/environment.yml
- modules/nf-core/bcftools/stats/main.nf
- modules/nf-core/bcftools/stats/meta.yml
- modules/nf-core/bcftools/stats/tests/main.nf.test
- modules/nf-core/bcftools/stats/tests/main.nf.test.snap
- modules/nf-core/bcftools/stats/tests/tags.yml
- workflows/epitopeprediction.nf
Added BCFTOOLS_STATS, which adds nice statistics for variant input #267
> Add bcftools/stats with multiQC integration

- CHANGELOG.md
- assets/schema_input.json
- workflows/epitopeprediction.nf
fixing bug with relative paths not being usable
> allow relative paths in samplesheet

- bin/summarize_results.py
This PR addresses two issues:
- error in wide table generation due to incorrect meta data column selection
- binder column would always be False
> Fixes for output file generation
